### ISSUE TITLE
Use redux-form forms where possible

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#110]
Nakoniec sa `redux-form` ukazali ako dobra volba, bolo by fajn do toho prehodit aj ostatne formulare.

Konkretne:
- [x] MFA form: @ujovlado: #113
- [x] Add developer form (v modale) @kacurez #118 
- [x] Select/Create vendor form (oba): @ujovlado ... #127 a #128 
- [x] Create app form: @ujovlado robil som edit app, tak toto prehodim razdva #111 
- [x] Login form: @ujovlado #113
- [x] Create account form @kacurez #121 
- [x] Forgot password form @kacurez #126

**Comment by ujovlado** [comment]
@kacurez zatial som sa pripisal k tym, co som robil + create app, ked tak si prirad dalsie :) ak mas daco ine, potom ked dokoncim svoje, pojdem zhora dole.

**Comment by kacurez** [comment]
ok prehodim ten zbytok, aspon si to osaham

**Comment by ujovlado** [comment]
dobre, super ... odpadne nam tam hodne handlovania error messages a pod., lebo redux-form si to drzi v svojom state ;)

**Comment by kacurez** [comment]
btw mi pride divne ze sa da selectnut `Please Select..` option, to bolo predtym ako disabled takze to neslo..
![image](https://user-images.githubusercontent.com/1412120/28464439-80a14eb8-6e25-11e7-90a4-4e37dcf39f64.png)

**Comment by ujovlado** [comment]
@kacurez to nehra rolu, ze je disabled ... ta error hlaska tam bude, kym nieco nevyberes

**Comment by ujovlado** [comment]
^ akurat teda to co pises je rozdiel v tom, ze uz ked som raz vybral nejaky typ, na "Please select" sa nedostanem -> je teda issue, ze sa tam vies dostat spat?

**Comment by kacurez** [comment]
to nieco na vybratie moze byt aj `Please select..` co mi pride divne ale zas kvoli tomu nebudem panikarit :)
Akurat ze som to bol zvyknuty osetrovat, a da sa to lahko poriesit aj tu, staci pridat `disabled` sem
https://github.com/keboola/developer-portal-ui/blob/master/src/scripts/components/common/form/fields.js#L241

**Comment by ujovlado** [comment]
Ja som to nejako velmi neriesil, ci to tam ma byt alebo nie. Teraz ked sa o tom bavime, mne sa zda divne, ze user dostane form s nejakou predvolenou value, no uz tuto predvolenu value nevie vybrat ... ale asi to nie je az taky problem. Keby to bol radio button, tiez sa nevie vratit k "prazdnemu" . Dam to tam.

**Comment by ujovlado** [comment]
Hotovson :tada:
