### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#193]
Zatial mi napada toto (pribezne doplnim)

- [x] init `production` and `development` config: @ujovlado #203 
- [x] setupnut novy project v sentry: @kacurez #202 
- [x] checknut ci idu vsetky req. cez proxy, aby sa dala zmenit API url ne jednom mieste: @ujovlado #201 
- [x] podobne plati pre redirecty/linky, pouzivame tam vlastnu `BASE_PATH` :@ujovlado #203 
- [x] rozbehat build (s tymto bude kusok zabava): @ujovlado // nakoniec takmer nic :) okrem ^
- [x] upravit travis aby robil build: @ujovlado: 1173190  
- [x] setupnut s3 a credentials: @ujovlado #204 
- [x] setupnut cloudfront smerujuci na s3: @ujovlado
- [x] setupnut route53 an nejaku domenu: @ujovlado
- [x] `index.html` by sa nemal cacheovat (aby si, ked prides znovu, dostal novu verziu): @ujovlado #204  (nastavene `no-cache`)

^ co sa da, idealne ako samostatne PR.

**Comment by ujovlado** [comment]
@kacurez potom sa dopise sem, ktore robis/chces robit, nech nerobime dvaja to iste ;)

**Comment by ujovlado** [comment]
s3 + cloudfront som skrtol ... bude to chciet nejaky apache/nginx, kvoli client side routingu

**Comment by kacurez** [comment]
nerozumiem, aky side routing? vsetky routy riesi found router a ten je na frontende..

**Comment by ujovlado** [comment]
ked prides priamo na napr. `/apps/rcp-anomaly`, tak ti s3ka prdne 404 ;) ... vsetko to musime posielat na index.html

**Comment by kacurez** [comment]
jiaj tak nebolo by lepsie to riesit cez hash? tj cesty by sa prefixovali #

**Comment by Halama** [comment]
stejný problém byl i u konzole kvůli tomu tam jeden v ECS apache který řeší jenom tohle:(
https://github.com/keboola/storage-api-console/blob/master/php-apache/storage-api-console.conf
nejde to už nějak vyřešit jenom přes CF + S3 website?

**Comment by Halama** [comment]
ale do url za hashem bych teda asi nesel:)

**Comment by ujovlado** [comment]
podla toho, co som cital na SO, by sa to mohlo dat ohackovat cez "Customizing Error Responses":
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/custom-error-pages.html
... je to trosku hack, ale skusim to

**Comment by ujovlado** [comment]
^ vyzera, ze to fici :)

**Comment by ujovlado** [comment]
v hlavickach tych odpovedi, co boli req. "na priamo" (napr. /auth/login, co neexistuje) ale bude "error from cloudfront", napr:
```
HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 471
Connection: keep-alive
Date: Wed, 09 Aug 2017 06:21:11 GMT
Last-Modified: Wed, 09 Aug 2017 06:13:05 GMT
ETag: "9a0c640befc19aca55bd925b78f6eb84"
Accept-Ranges: bytes
Server: AmazonS3
X-Cache: Error from cloudfront
Via: 1.1 1463b274b31e0310acc7c754b8b5a550.cloudfront.net (CloudFront)
X-Amz-Cf-Id: -ZkLPK0Ebud6-cfTNtA4r-VrDENo51RRG_xeYPj8Et_9nLILa8MBFg==
```

**Comment by ujovlado** [comment]
Vsetko done, to sentry este doladime v tom PR.
