### ISSUE TITLE
Jack review

### ISSUE THREAD

**Issue by jancermak** [keboola/developer-portal-ui#225]
————vizualni zmeny nez me kacurez zastavil :-) —————
**Home**
- [x] font — pouzit keboola font — Gotham Rounded (Jan vi jak zprovoznit) // done #227 
- [x] dodat celou tutu cast — http://take.ms/x1Cmd // done #228 
- [x] stin pod aplikaci — http://take.ms/Kumi9 — pokud to nebude delat problemy  —`box-shadow: 0 24px 32px 0 rgba(82,97,115,0.1);` // uz spravene
- [x] ~hover efekt nad aplikaci (to chybelo ode me) popsano v obrazku —  http://take.ms/FomSO — `box-shadow: 0 24px 32px 0 rgba(82,97,115,0.3);`~ // presunute do #231
- [x] btn more app odsadit od boxu s apkkama - mezera cca 75px — http://take.ms/JtjdJ // done #232 
- [x] odkazy v paticce podtrzene http://take.ms/c7XxR // done #229
- [x] padding left a rigt u tlacitek 24px — http://take.ms/g07lg // done #230 
- [x] podnadpis- zvetsit velikost fontu, padding stejny ze shora i z dola — http://take.ms/zX4bT // done #232 
- [x] nadpis mensi — http://take.ms/n3Ogt  // done #232 
```
.top-used-apps {
	color: #2AB4E2;
	font-family: "Gotham Rounded";
	font-size: 24px;
	font-weight: bold;
	line-height: 36px;
	text-align: center;
}
```

**Apps - neprihlaseny user**
—————————————————————
Flow aplikace

**Comment by ujovlado** [comment]
@jancermak inac, kludne si s tym daj pauzu, tie CSS sme este neladili

radsej by som to spravil tak, ze spravis review, az to bude ready.

**Comment by ujovlado** [comment]
@jancermak nechcem ti vyrabat robotu, vela z tych veci je jasnych z designu ... asi sme sa uplne nepochopili :)

**Comment by ujovlado** [comment]
Tieto homepage veci su fixes, zatvaram. Na dalsie casti resp. na ten "flow" poriesme prosim ako samostantne issue.

Pripominam, ze CSS zatial ready z nasej strany nie su.
