### ISSUE TITLE
Check if all modals have notification

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#248]
Vsetky modaly by mali po zavreti vyhodit nejaku success message.

- [x] Home/Invite a developer #247 
- [x] Home/Edit app icon #246 
- [x] Home/App approval req. #249
- [x] Home/App deletion #261 
- [x] Home/Remove vendor or leave vendor #262
- [x] ~Create service account~ // netreba
- [x] Admin/Change vendors of developer #260
- [x] Admin app approval: 15ad6c0
- [x] Admin app removal: 9e6a929
- [x] Admin vendor update/create: #264 
- [x] admin vendor approval: 933ae7c

**Comment by ujovlado** [comment]
Vyzera, ze uz je to vsade, zatvaram.
