### ISSUE TITLE
Update store after app approval request/confirm/rejection

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#272]
- related to #271 a https://github.com/keboola/developer-portal/issues/148
- aby sa dal vrateny object rovno pouzit a na zaklade toho upravit store -> okamzita zmena view

Casti:

- [x] home: Publishing req. Takmer done, zatial to ale nepodporuje API: https://github.com/keboola/developer-portal/issues/148#issuecomment-327579741, WIP tu: #279 
- [x] admin: Approve app #280 
- [x] admin: Reject app #280
