### ISSUE TITLE
Init JS

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#3]
Mali by sme initnut tento projekt tak, aby bolo priblizne jasne, co a ako robit.

- [x] react-router: nieco som nastrelil, uvidime ako s tym dalej
- [x] rozdelenie public/private cast: zaklad je, je tam navbar
- [x] init bootstrap a UI: issue https://github.com/keboola/developer-portal-ui/issues/1, zatial mozeme ficat aj bez toho a robit to s default bootstrap markupom
- [x] dummy auth, aby sa mohlo robit na public strankach a clovek vedel ako to cca bude vyzerat
- [x] realna auth voci API #5 
- [x] proxy pre devel mode (vid. create-react-app docs) 2b56217ffcf5f57eba6fe615ca9a5c20e945effa
- [x] test nacitania dat (cele to moze byt postavene na `fetch()`) d1df93f258451a7ac6059e400fb109819239fe71
- [x] s tym suvisi store #12 
- [ ] ~cancellovat requesty pri zmene routy~ #38 
- [x] poriesit layouty (sign in je napr. "simple", ostatne su s navbarom)
- [x] travis setup #17

**Comment by ujovlado** [comment]
To proxovanie fici, pozeram, ze na pozadi to pusti Express server :)

**Comment by ujovlado** [comment]
je toto vcelku ujasnene, az na "cancellovat requesty pri zmene routy"  ... to som zatial neskumal ... a asi by slo pouzit `redux-observable` (https://github.com/redux-observable/redux-observable), no zatial na to prdim, nech sa tam nezavadza dalsia magia, kym nie sme uplne zoznameny s reduxom

**Comment by ujovlado** [comment]
jo, je to vlastne ready :) tu issue som presunul
